tts_tool: fasterqwen # May be openai, fasterqwen, indextts, or load

openai:
  model: "tts-1-hd"
  voice: "ash"
  api_key: "./api_key.txt"
  speed: 1

fasterqwen: # settings for a local FasterQWen TTS server with multi-speaker support
  api: "http://localhost:7860" # base URL of the server
  # model_id: "models/Qwen3-TTS-12Hz-1.7B-VoiceDesign"
  model_id: "models/Qwen3-TTS-12Hz-1.7B-Base"
  # model_id: "models/Qwen3-TTS-12Hz-1.7B-CustomVoice"
  mode: "voice_clone" # voice_clone, custom or voice_design
  language: "Auto" # e.g. Auto, Chinese, English, Japanese, Korean, German, French, Russian, Portuguese, Spanish, Italian
  speaker: [
      "Vivian",
      "Serena",
      "Uncle_Fu",
      "Dylan",
      "Eric",
      "Ryan",
      "Aiden",
      "Ono_Anna",
      "Sohee",
    ] # required for custom mode
  # { id: 'Vivian',   desc: 'Chinese — Bright young female' },
  # { id: 'Serena',   desc: 'Chinese — Warm gentle female' },
  # { id: 'Uncle_Fu', desc: 'Chinese — Seasoned low male' },
  # { id: 'Dylan',    desc: 'Chinese — Youthful Beijing male' },
  # { id: 'Eric',     desc: 'Chinese (Sichuan) — Lively male' },
  # { id: 'Ryan',     desc: 'English — Dynamic male' },
  # { id: 'Aiden',    desc: 'English — Sunny American male' },
  # { id: 'Ono_Anna', desc: 'Japanese — Playful female' },
  # { id: 'Sohee',    desc: 'Korean — Warm female' },
  # instruct: "体现撒娇稚嫩的萝莉女声，音调偏高且起伏明显，营造出黏人、做作又刻意卖萌的听觉效果。" # for voice_design mode
  instruct: [
      "采用高亢的男性嗓音，语调随兴奋情绪不断上扬，以快速而充满活力的节奏传达信息。音量要足够响亮，近乎喊叫，以体现紧迫感。发音务必清晰精准、字字分明，让每个词都铿锵有力。整体表达需流畅自然、明亮生动，富有戏剧性，展现出外向、自信且张扬的个性，同时传递出一种威严而宏大的宣告语气，洋溢着满溢的激动之情",
      "展现出悲苦沙哑的声音质感,语速偏慢,情绪浓烈且带有哭腔,以标准普通话缓慢诉说,情感强烈,语调哀怨高亢,音高起伏大。",
      "体现撒娇稚嫩的萝莉女声，音调偏高且起伏明显，营造出黏人、做作又刻意卖萌的听觉效果。",
      "性别: 男性. 音高: 男性低沉音域，音高稳定. 语速: 语速稍快，节奏紧凑. 音量: 音量洪亮，力度强劲. 年龄: 中老年. 清晰度: 发音清晰，字句有力. 流畅度: 表达流畅，一气呵成. 口音: 标准普通话. 音色质感: 嗓音浑厚，略带沙哑感. 情绪: 严肃告诫，指令明确. 语调: 命令式语调，强调果断. 性格: 权威果断，不容置喙.",
      "性别: 男性 音高: 男性低沉音区，偶有拔高. 语速: 初始平稳，后段因激动逐渐加快. 音量: 初始音量正常，后段逐渐提高至喊叫. 年龄: 中年男性. 清晰度: 吐字清晰，发音准确. 流畅度: 言语连贯，表达自然. 口音: 标准普通话发音. 音色质感: 音质略带粗砺，富有力量感. 情绪: 初始不耐烦，迅速转为恼怒斥责. 语调: 质问命令式，语带不悦与威慑. 性格: 急躁易怒，态度强硬.",
      "自然感的女声，语调活泼带笑意，模仿别人‘嘘’你时压低嗓音，就是平时聊天的感觉",
      "角色姓名：林怀岳音色信息：音量洪亮，音域低沉，力度感强的中年男性声音。身份背景：某国家重点科研项目首席顾问，年近七十的资深战略科学家。曾参与国家重大科技攻关工程，历经数十年风雨，见证了从落后追赶到自主创新的艰难历程。现任国家科技咨询委员会终身荣誉委员，仍坚持在一线培养青年人才，为国家战略发展建言献策。外貌特征：身形挺拔，两鬓斑白，眉宇间刻着岁月沉淀的坚毅。常着深色中山装或简洁正装，眼神沉静而锐利，举手投足间自带威严与从容。性格特质：意志如钢，信念坚定，面对挑战从不退缩；胸怀家国，心系民族未来，将个人命运与国家兴衰紧密相连；严谨自律，言出必行，话语中充满责任感与历史担当；外冷内热，表面严肃，实则对后辈寄予厚望，甘为人梯。人生信条：“我们这一代人，不是为了站在光里，而是为了把路铺到光里。”",
      "模拟成熟性感的御姐音色，声音略带磁性且沉稳，语速不快不慢，语调充满自信和一丝挑逗，尾音可以稍微拖长并上扬，给人一种游刃有余的掌控感。",
    ] # for voice_design mode
  ref_audio: [
      "D:/ReferenceAudio/古话说，天下大势，分久必合，合久必分。.wav",
      "D:/ReferenceAudio/这是公子先前所赐！.wav",
      "D:/ReferenceAudio/大哥的问题自然也就是我的问题！.wav",
      "D:/ReferenceAudio/那些死去士兵的意义，将由我们来赋予。.wav",
      "D:/ReferenceAudio/哎，你今天有空吗？我们能不能聊聊这件事啊？.wav",
      "D:/ReferenceAudio/哥哥，你回来啦，人家等了你好久好久了，要抱抱！.wav",
      "D:/ReferenceAudio/真正的朋友是会理解你的。你可以找个时间跟他们好好说说你的感受，也许他们就能明白了。.wav",
      "D:/ReferenceAudio/好舍不得你啊，哥哥，你会想我吗？.mp3",
      "D:/ReferenceAudio/在浩瀚的宇宙当中，有一颗美丽的蓝色星球叫地球。.wav",
    ] # for voice_clone mode

indextts: # settings for an IndexTTS Gradio server
  api: "http://localhost:7860"
  ref_audio: [
      "D:/ReferenceAudio/古话说，天下大势，分久必合，合久必分。.wav",
      "D:/ReferenceAudio/这是公子先前所赐！.wav",
      "D:/ReferenceAudio/大哥的问题自然也就是我的问题！.wav",
      "D:/ReferenceAudio/那些死去士兵的意义，将由我们来赋予。.wav",
      "D:/ReferenceAudio/哎，你今天有空吗？我们能不能聊聊这件事啊？.wav",
      "D:/ReferenceAudio/哥哥，你回来啦，人家等了你好久好久了，要抱抱！.wav",
      "D:/ReferenceAudio/真正的朋友是会理解你的。你可以找个时间跟他们好好说说你的感受，也许他们就能明白了。.wav",
      "D:/ReferenceAudio/好舍不得你啊，哥哥，你会想我吗？.mp3",
      "D:/ReferenceAudio/在浩瀚的宇宙当中，有一颗美丽的蓝色星球叫地球。.wav",
    ]
  lang_choice: "ZH"  # May be ZH, EN, ES, AR, or JA
  # emo_ref_path: "D:/ReferenceAudio/emotion.wav"

load:
  path: "./tmp/"
  # path: "./tmp_demo/"
